<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SignAssembly>True</SignAssembly>
    <DelaySign>False</DelaySign>
    <AssemblyOriginatorKeyFile>..\TOTP.Core\totp-sign-key.snk</AssemblyOriginatorKeyFile>
    <PublicSign>true</PublicSign>
    <NoWarn>$(NoWarn);CS8002</NoWarn>
    <UserSecretsId>eae90785-030b-456f-b23c-5ab39239447f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOTP.Camera.OpenCv\TOTP.Camera.OpenCv.csproj" />
    <ProjectReference Include="..\TOTP.Core\TOTP.Core.csproj" />
    <ProjectReference Include="..\TOTP.Infrastructure\TOTP.Infrastructure.csproj" />
    <ProjectReference Include="..\TOTP.Platform.Linux\TOTP.Platform.Linux.csproj" />
    <ProjectReference Include="..\TOTP.Platform.MacOS\TOTP.Platform.MacOS.csproj" />
    <ProjectReference Include="..\TOTP.Platform.Windows\TOTP.Platform.Windows.csproj" />
    <ProjectReference Include="..\TOTP.UI.Avalonia.Desktop\TOTP.UI.Avalonia.Desktop.csproj" />
    <ProjectReference Include="..\TOTP.UI.Avalonia.Mobile\TOTP.UI.Avalonia.Mobile.csproj" />
    <ProjectReference Include="..\TOTP.Updater\TOTP.Updater.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Fixtures\LegacySettings\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\TOTP.UI.Avalonia.Shared\Styles\SharedStyles.axaml"
          Link="Fixtures\Avalonia\SharedStyles.axaml"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\TOTP.UI.Avalonia.Desktop\App.axaml"
          Link="Fixtures\Avalonia\App.axaml"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- In TOTP.Tests.csproj -->
  <Target Name="RunTestsAfterBuild" AfterTargets="Build" Condition="'$(CI)' != 'true' AND '$(RunTestsOnBuild)' == 'true'">
    <Exec Command="dotnet test &quot;$(MSBuildProjectFullPath)&quot; --configuration $(Configuration) --no-build" />
  </Target>


</Project>
