<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\TOTP.Core\totp-sign-key.snk</AssemblyOriginatorKeyFile>
    <NoWarn>$(NoWarn);CS8002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TOTP.Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010099f4449145c5f37f4715bbfc7b3393d2fdfd569adcb13022e232f8f06c45337f89a82a346e35ed1695174781565904b34d81922c0d1fbe62febeda403133dcbe7d871c76023605d7bdd9ee6f43771b1c1e248af86424fab9f96f0aceb1d912d52e268cd125f36ff9dcf16e99c410f60a93dac22efbebc5518edf10dd160eeac7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="NSec.Cryptography" Version="26.4.0" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOTP.Core\TOTP.Core.csproj" />
    <ProjectReference Include="..\TOTP.DAL\TOTP.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Branding\issuer-resolver.v1.json"
                      LogicalName="TOTP.Infrastructure.Branding.issuer-resolver.v1.json" />
  </ItemGroup>

</Project>
